services:
  database:   # Postgresql Database for backend.
    image: postgres:15-alpine
    container_name: zabbix-dedicated-database
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=zabbix
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks: # Database have to be available in all networks
      zabbix:
        ipv4_address: 172.20.240.1

  server:     # Zabbix backend
    image: zabbix/zabbix-server-pgsql:alpine-${ZBX_VERSION}
    container_name: zabbix-backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_SERVER_HOST=172.20.240.1
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    networks: # Backend have to be accessible by frontend, and have ability to access database
      zabbix:
        ipv4_address: 172.20.240.2

  snmptraps:  # SNMP Traps
    image: zabbix/zabbix-snmptraps:alpine-${ZBX_VERSION}
    container_name: zabbix-snmp-traps
    restart: unless-stopped
    depends_on:
      - server
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
      - mibs:/usr/share/snmp/mibs:ro
    ports:
      - "162:1162/udp"
    networks:
      zabbix:
        ipv4_address: 172.20.240.3

  frontend:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-${ZBX_VERSION}
    container_name: zabbix-frontend
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - ZBX_SERVER_HOST=172.20.240.2
      - DB_SERVER_HOST=172.20.240.1
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=zabbix
    networks:
      zabbix:
        ipv4_address: 172.20.240.4
    ports:
      - "8443:8443"
      - "8080:8080"
    volumes:
      - nginx:/etc/ssl/nginx:ro

  agent2:
    image: zabbix/zabbix-agent2:alpine-${ZBX_VERSION}
    container_name: zabbix-linux-agent-v2
    restart: unless-stopped
    environment:
      - ZBX_HOSTNAME=172.20.240.5
      - ZBX_SERVER_HOST=172.20.240.2
    networks:
      zabbix:
        ipv4_address: 172.20.240.5
    ports:
      - "10050:10050"

volumes:
  db_data:    # This volume persists database data
  snmptraps:  # For SNMP traps
  mibs:       # For SNMP traps
  nginx:      # Frontend`s nginx files

networks:
  # Network map (root):   172.20.0.0/16
  # Network               172.20.240.0/20
  # Database              172.20.240.1
  # Zabbix server         172.20.240.2
  # SNMP Traps            172.20.240.3
  # Frontend              172.20.240.4
  # Agent                 172.20.240.5
  zabbix:
    ipam:
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"
          ip_range: "172.20.240.0/20"