services:
  database:   # Postgresql Database for backend.
    image: postgres:15-alpine
    container_name: zabbix-dedicated-database
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=zabbix
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks: # Database have to be available in all networks
      zabbix:
        ipv4_address: 172.20.240.1

  server:     # Zabbix backend
    image: zabbix/zabbix-server-pgsql
    container_name: zabbix-backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_SERVER_HOST=172.20.240.1
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    networks: # Backend have to be accessible by frontend, and have ability to access database
      zabbix:
        ipv4_address: 172.20.240.2

volumes:
  db_data:    # This volume persists database data

networks:
  # Network map (root):   172.20.0.0/16
  # Network               172.20.240.0/20
  # Database              172.20.240.1
  # Zabbix server         172.20.240.2
  zabbix:
    ipam:
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"
          ip_range: "172.20.240.0/20"