services:
  database:   # Postgresql Database for backend.
    image: postgres:15-alpine
    container_name: zabbix-dedicated-database
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=zabbix
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks: # Database have to be available in all networks
      - zabbix
      - db

  server:     # Zabbix backend
    image: zabbix/zabbix-server-pgsql
    container_name: zabbix-backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_SERVER_HOST="zabbix-dedicated-database"
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    networks: # Backend have to be accessible by frontend, and have ability to access database
      - zabbix
      - db

volumes:
  db_data:    # This volume persists database data

networks:
  zabbix:     # This network is for connecting frontend and backend
  db:         # This network is for connecting backend with database